### ISSUE TITLE
[Question] Method to fetch old rank

### ISSUE THREAD

**Issue by coderhs** [shijithraghav/alexa_scrapping#2]
Curious on your choice of code to fetch the old rank. As going through all the ranks seems to be unnecessary and becomes slower with the number of ranks with respect to the a website increases.

```
@website.ranks.each do |rank|
        @old_rank = rank.rank
 end
```

**Comment by shijithraghav** [comment]
As you said, the process will be slower when it comes to large number of domains. so , I changed the code to

`@old_rank = @website.ranks.first.rank`
